stages:
  - lint
  - build
  - test
  - release

lint:
  stage: build
  tags:
    - npm
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js "{src,apps,libs,test}/**/*.ts"

build:
  stage: build
  tags:
    - npm
  script:
    - npm install
    - npm run build

test:
  stage: test
  tags:
    - npm
  script:
    - echo "Execute tests"

# release:
#   stage: release
#   tags:
#     - priv
#   script:
#     - docker build -t issue-service .
#   # only:
#   #   - master

  


  