stages:
  - lint
  - build
  - test
  - release

lint:
  stage: build
  tags:
    - npm
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js "{src,apps,libs,test}/**/*.ts"

build:
  stage: build
  tags:
    - npm
  script:
    - npm install
    - npm run build

test:
  stage: test
  tags:
    - npm
  script:
    - echo "Execute tests"

release:
  stage: release
  tags:
    - microservices
  variables:
    UPSTREAM_IMAGE: $THM_DOCKER_REGISTRY/microservices-ss2021/$CI_PROJECT_NAME
  before_script:
    - docker login -u gitlab-ci-token -p $DOCKER_CI_TOKEN $THM_DOCKER_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE .
    - docker push $UPSTREAM_IMAGE:latest
  only:
    - master